### ISSUE TITLE
Moment dependency needs to be updated due to security advisory

### ISSUE THREAD

**Issue by robwalkerexp** [TomFrost/Bristol#26]
Moment should be updated to at least 2.11.2.

https://nodesecurity.io/advisories/55

**Comment by MarkHerhold** [comment]
Bristol's version range isn't preventing you from using newer versions of moment.

```json
  "dependencies": {
    "moment": "^2.14.1"
  }
```

**Comment by TomFrost** [comment]
Moment's been forced to `^2.17.1` in the latest master.

**Comment by MartijnR** [comment]
Would be great to publish a new version with this change.
