### ISSUE TITLE
Use json-stringify-safe for json formatter

### ISSUE THREAD

**Issue by rooftopsparrow** [TomFrost/Bristol#35]
Hello @TomFrost and contributors,

Wondering if you'd be open to taking on another dependency and changing the default json formatter to use [json-stringify-safe](https://www.npmjs.com/package/json-stringify-safe) to protect crashing the process when trying to stringify a circular structure?

I'm willing to make a PR if this is something you'd like.

Thanks 👍

**Comment by TomFrost** [comment]
Another good suggestion!

My only immediate concern about this would be serialization speed. I'd love to see a benchmark of `JSON.stringify` versus that lib-- if you wanted to convert Bristol and test that, I wouldn't be opposed!

**Comment by rooftopsparrow** [comment]
Awesome! 

Since there are no benchmarking tests in Bristol right now, I'll make a PR adding some initial benchmarks to establish a baseline of performance. However, I have no clue what I'm doing in terms of benchmarking, so it'd be _awesome_ to get some feedback on things you'd like to see benchmarked.

**Comment by MarkHerhold** [comment]
@TomFrost json-stringify-safe is infinitely faster on circular references ;)

**Comment by yknx4** [comment]
PR #41
