### ISSUE TITLE
v0.3.3 not at latest on npm

### ISSUE THREAD

**Issue by dogfoodsilo4** [TomFrost/Bristol#39]
I'm writing a custom formatter that requires logUtils.  

However, the latest version of bristol on npm ^0.3.3 does not appear to include the commit from 16th December that made logUtils public: -

https://github.com/TomFrost/Bristol/commit/cacb279674bb32b50e87a8c2b02b422d4f032bec

If I run:

npm install bristol --save

Local package.json reports:

  "dependencies": {
    "bristol": "^0.3.3",
    ...
  },

but node_modules\bristol\bristol.js is missing the changes.

see line 364 & 356:
module.exports = new Bristol();
module.exports.Bristol = Bristol;

It's missing the last 2 lines:

module.exports._logUtil = logUtil
module.exports.Bristol.logUtil = logUtil 

The source on github is correct, so is it npm that is holding an older version?

Thanks for looking.  Love bristol logging btw :)

**Comment by dogfoodsilo4** [comment]
I'm doing this for now:

let logUtil = require("./node_modules/bristol/lib/Util");

...but obviously this is only temporary.

**Comment by TomFrost** [comment]
The fix for this is coming soon :). Bristol doesn't have version branches (yet) so current development is all in master and not necessarily published. I had to take a small break from Bristol development to make a major release of Squiss, but now I'm back to getting Bristol to 1.0.

**Comment by TomFrost** [comment]
(Closing since this is part of the normal dev cycle)
